version: '3'

services:
  webapp:
    container_name: chat
    build:
      context: .
    depends_on:
      - broker
    ports:
      - "8080:8080"
    networks:
      - chat_bridge

  broker:
    container_name: rabbit_chat
    image: rabbitmq:latest
    hostname: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - chat_bridge

networks:
  chat_bridge:
    external:
      name: chat_bridge



